export const CAR_CATALOG: Record<string, string[]> = {
  Acura: ["MDX", "RDX", "TLX"],
  "Alfa Romeo": ["Giulia", "Stelvio", "Tonale"],
  "Aston Martin": ["DB11", "DBS", "DBX", "Vantage"],
  Audi: ["A3", "A4", "A5", "A6", "A7", "A8", "e-tron GT", "Q2", "Q3", "Q4 e-tron", "Q5", "Q7", "Q8", "Q8 e-tron"],
  Bentley: ["Bentayga", "Continental GT", "Flying Spur"],
  BMW: ["1 Series", "2 Series", "3 Series", "4 Series", "5 Series", "7 Series", "8 Series", "i4", "i5", "i7", "iX", "X1", "X2", "X3", "X4", "X5", "X6", "X7"],
  BYD: ["Atto 3", "Dolphin", "Han", "Seal", "Seal U", "Sealion 6", "Tang"],
  Cadillac: ["CT5", "Escalade", "XT4", "XT5", "XT6"],
  Changan: ["Alsvin", "CS35 Plus", "CS55 Plus", "CS75 Plus", "Uni-K", "Uni-T", "Uni-V"],
  Chery: ["Arrizo 6", "Tiggo 4", "Tiggo 7", "Tiggo 8"],
  Chevrolet: ["Blazer", "Camaro", "Captiva", "Groove", "Malibu", "Silverado", "Spark", "Suburban", "Tahoe", "Trailblazer", "Traverse"],
  Citroen: ["Berlingo", "C3", "C4", "C5 Aircross"],
  Deepal: ["L07", "S07"],
  Dodge: ["Challenger", "Charger", "Durango", "Ram 1500"],
  Exeed: ["LX", "TX", "TXL", "VX"],
  Ferrari: ["296 GTB", "488", "Portofino", "Purosangue", "Roma", "SF90"],
  Ford: ["Bronco", "Edge", "Escape", "Expedition", "Explorer", "F-150", "Fusion", "Mustang", "Ranger", "Territory"],
  GAC: ["Emkoo", "Emzoom", "GS3", "GS4", "GS8"],
  Geely: ["Coolray", "Okavango", "Tugella"],
  Genesis: ["G70", "G80", "G90", "GV70", "GV80"],
  GMC: ["Acadia", "Canyon", "Sierra", "Terrain", "Yukon"],
  "Great Wall": ["Cannon", "Wingle"],
  Haval: ["Dargo", "H2", "H6", "Jolion"],
  Honda: ["Accord", "City", "Civic", "CR-V", "HR-V", "Odyssey", "Passport", "Pilot"],
  Hyundai: ["Accent", "Creta", "Elantra", "Ioniq 5", "Ioniq 6", "Kona", "Palisade", "Santa Fe", "Sonata", "Staria", "Tucson", "Venue"],
  Infiniti: ["Q50", "Q60", "QX50", "QX55", "QX60", "QX80"],
  JAECOO: ["J7", "J8"],
  Jeep: ["Cherokee", "Compass", "Gladiator", "Grand Cherokee", "Renegade", "Wrangler"],
  Jetour: ["Dashing", "T2", "X70", "X90"],
  Kia: ["Carnival", "Cerato", "EV6", "Picanto", "Seltos", "Sonet", "Sorento", "Sportage", "Stinger", "Telluride"],
  Lamborghini: ["Aventador", "Huracan", "Revuelto", "Urus"],
  "Land Rover": ["Defender", "Discovery", "Evoque", "Range Rover", "Range Rover Sport", "Range Rover Velar"],
  Lexus: ["ES", "GX", "IS", "LC", "LS", "LX", "NX", "RX", "UX"],
  Lincoln: ["Aviator", "Corsair", "Navigator"],
  Maserati: ["Ghibli", "Grecale", "GranTurismo", "Levante", "Quattroporte"],
  Mazda: ["CX-30", "CX-5", "CX-60", "CX-9", "Mazda3", "Mazda6"],
  "Mercedes-Benz": ["A-Class", "C-Class", "CLA", "E-Class", "EQE", "EQS", "G-Class", "GLA", "GLB", "GLC", "GLE", "GLS", "S-Class"],
  MG: ["4 EV", "HS", "MG5", "MG6", "RX5", "ZS"],
  Mitsubishi: ["ASX", "Eclipse Cross", "L200", "Montero", "Outlander", "Pajero", "Xpander"],
  Nissan: ["Altima", "Armada", "Kicks", "Maxima", "Navara", "Patrol", "Pathfinder", "Sentra", "Sunny", "Tiida", "X-Trail", "Xterra"],
  OMODA: ["C5", "S5"],
  Peugeot: ["208", "2008", "3008", "5008", "508"],
  Porsche: ["911", "Cayenne", "Cayenne Coupe", "Macan", "Panamera", "Taycan"],
  Renault: ["Arkana", "Captur", "Duster", "Koleos", "Logan", "Megane", "Symbol"],
  "Rolls-Royce": ["Cullinan", "Ghost", "Phantom", "Spectre", "Wraith"],
  Tesla: ["Cybertruck", "Model 3", "Model S", "Model X", "Model Y"],
  Toyota: ["Avalon", "bZ4X", "Camry", "Corolla", "Crown", "Fortuner", "Hilux", "Land Cruiser", "Prado", "Prius", "Raize", "RAV4", "Rush", "Sequoia", "Veloz", "Yaris"],
  Volkswagen: ["Atlas", "Golf", "ID.4", "ID.6", "Jetta", "Passat", "Polo", "Teramont", "Tiguan", "Touareg"],
  Volvo: ["EX30", "EX90", "S60", "S90", "V60", "XC40", "XC60", "XC90"],
  XPENG: ["G6", "G9", "P7"],
  Other: ["Other"],
};

export const CAR_MAKES = Object.keys(CAR_CATALOG);
