export const CAR_CATALOG: Record<string, string[]> = {
  Toyota: ["Camry", "Corolla", "Land Cruiser", "Prado", "Hilux", "RAV4", "Yaris", "Fortuner", "Avalon"],
  Nissan: ["Altima", "Patrol", "Sunny", "X-Trail", "Kicks", "Maxima", "Pathfinder", "Sentra"],
  Honda: ["Accord", "Civic", "CR-V", "Pilot", "HR-V"],
  Hyundai: ["Elantra", "Sonata", "Tucson", "Santa Fe", "Accent", "Palisade"],
  Kia: ["Sportage", "Sorento", "Optima", "Cerato", "Telluride", "Seltos"],
  Ford: ["F-150", "Explorer", "Expedition", "Mustang", "Edge", "Escape"],
  Chevrolet: ["Tahoe", "Suburban", "Malibu", "Camaro", "Silverado", "Trailblazer"],
  GMC: ["Yukon", "Sierra", "Acadia", "Terrain"],
  Jeep: ["Grand Cherokee", "Wrangler", "Cherokee", "Compass"],
  BMW: ["3 Series", "5 Series", "7 Series", "X3", "X5", "X6", "X7"],
  "Mercedes-Benz": ["C-Class", "E-Class", "S-Class", "GLE", "GLC", "G-Class"],
  Audi: ["A4", "A6", "A8", "Q5", "Q7", "Q8"],
  "Land Rover": ["Range Rover", "Range Rover Sport", "Discovery", "Defender", "Evoque"],
  Lexus: ["ES", "LS", "RX", "GX", "LX", "NX"],
  Porsche: ["Cayenne", "Macan", "Panamera", "911", "Taycan"],
  Volkswagen: ["Tiguan", "Passat", "Jetta", "Atlas", "Golf"],
  Mitsubishi: ["Pajero", "Outlander", "Montero", "ASX"],
  Mazda: ["CX-5", "CX-9", "Mazda3", "Mazda6"],
  Infiniti: ["QX60", "QX80", "Q50", "QX56"],
  Genesis: ["G70", "G80", "G90", "GV80"],
  Tesla: ["Model 3", "Model S", "Model X", "Model Y"],
  Bentley: ["Bentayga", "Continental GT", "Flying Spur"],
  "Rolls-Royce": ["Cullinan", "Phantom", "Ghost", "Wraith"],
  Ferrari: ["488", "Roma", "Portofino", "SF90"],
  Lamborghini: ["Urus", "Huracan", "Aventador"],
  Maserati: ["Levante", "Ghibli", "Quattroporte"],
  Other: ["Other"],
};

export const CAR_MAKES = Object.keys(CAR_CATALOG);
