// Dubai areas (master communities) and the sub-communities inside them.
// Same shape as CAR_CATALOG: pick the area first, then the community.
// The five areas Carwaj operates in are listed first in the picker via PRIORITY_AREAS.
export const DUBAI_COMMUNITIES: Record<string, string[]> = {
  "Arabian Ranches 1": [
    "Al Mahra",
    "Al Reem 1",
    "Al Reem 2",
    "Al Reem 3",
    "Alma",
    "Alvorada 1",
    "Alvorada 2",
    "Alvorada 3",
    "Alvorada 4",
    "Aseel",
    "Golf Homes",
    "Hattan 1",
    "Hattan 2",
    "Hattan 3",
    "La Avenida 1",
    "La Avenida 2",
    "Mirador",
    "Mirador La Coleccion 2",
    "Palmera 1",
    "Palmera 2",
    "Palmera 3",
    "Palmera 4",
    "Polo Homes",
    "Saheel 1",
    "Saheel 2",
    "Saheel 3",
    "Saheel 4",
    "Savannah 1",
    "Savannah 2",
    "Savannah 3",
    "Terra Nova",
  ],
  "Arabian Ranches 2": [
    "Azalea",
    "Camelia",
    "Casa",
    "Lila",
    "Palma",
    "Rasha",
    "Reem",
    "Rosa",
    "Samara",
    "Yasmin",
  ],
  "Arabian Ranches 3": [
    "Anya",
    "Anya 2",
    "Bliss",
    "Bliss 2",
    "Caya",
    "Elie Saab Villas",
    "Joy",
    "June",
    "May",
    "Raya",
    "Ruba",
    "Spring",
    "Sun",
  ],
  "Town Square": [
    "Ascot Residences",
    "Aria on The Park",
    "Ayala",
    "Elaya",
    "Fia",
    "Grove",
    "Hayat Boulevard",
    "Hayat Townhouses",
    "Holland Gardens",
    "Jenna",
    "Kaya",
    "Lana on The Park",
    "Liva",
    "Maha Townhouses",
    "Naseem Townhouses",
    "Noor Townhouses",
    "Ora",
    "Parkside",
    "Parkviews",
    "Rawda Apartments 1",
    "Rawda Apartments 2",
    "Reem Townhouses",
    "Safi Apartments",
    "Safi Townhouses",
    "Sama Townhouses",
    "Shams Townhouses",
    "Symphony on The Park",
    "The Diplomat Residences",
    "The Hamilton",
    "The Mayfair",
    "The Regent Residences",
    "UNA Apartments",
    "Warda Apartments",
    "Zahra Apartments",
    "Zahra Breeze Apartments",
    "Zahra Townhouses",
  ],
  "Tilal Al Ghaf": [
    "Alaya",
    "Alaya Beach",
    "Alaya Gardens",
    "Amara",
    "Aura",
    "Aura Gardens",
    "Elan",
    "Elysian Mansions",
    "Harmony 1",
    "Harmony 2",
    "Harmony 3",
    "Lanai Islands",
    "Plagette 32",
    "Serenity Mansions",
  ],

  "Akoya (DAMAC Hills)": [
    "Artesia",
    "Brookfield",
    "Calero",
    "DAMAC Villas by Paramount",
    "Flora",
    "Golf Promenade",
    "Golf Town",
    "Longview",
    "Loreto",
    "Pelham",
    "Picadilly Green",
    "Rockwood",
    "Silver Springs",
    "The Field",
    "The Park Villas",
    "The Turf",
    "Topanga",
    "Trinity",
    "Trump Estates",
    "Veneto",
    "Whitefield",
  ],
  "Al Barari": [],
  "Al Barsha": [
    "Al Barsha 1",
    "Al Barsha 2",
    "Al Barsha 3",
    "Al Barsha Heights",
    "Al Barsha South",
  ],
  "Al Furjan": [
    "Dubai Style",
    "Masakin Al Furjan",
    "Murooj Al Furjan",
    "North Village",
    "Quortaj",
    "South Village",
  ],
  "Al Jaddaf": [],
  "Al Khawaneej": ["Al Khawaneej 1", "Al Khawaneej 2"],
  "Al Mizhar": ["Al Mizhar 1", "Al Mizhar 2"],
  "Al Qusais": [],
  "Al Quoz": ["Al Quoz 1", "Al Quoz 2", "Al Quoz 3", "Al Quoz 4"],
  "Al Safa": ["Al Safa 1", "Al Safa 2"],
  "Al Warqaa": [
    "Al Warqaa 1",
    "Al Warqaa 2",
    "Al Warqaa 3",
    "Al Warqaa 4",
    "Al Warqaa 5",
  ],
  "Al Wasl": [],
  "Arjan": [],
  "Bluewaters Island": [],
  "Business Bay": [],
  "Cherrywoods": [],
  "City Walk": [],
  "DAMAC Hills 2 (Akoya Oxygen)": [
    "Albizia",
    "Amargo",
    "Amazonia",
    "Aquilegia",
    "Aster",
    "Avencia",
    "Basswood",
    "Camelia",
    "Centaury",
    "Claret",
    "Coursetia",
    "Eterno",
    "Fiora",
    "Hajar Stone Villas",
    "Hawthorn",
    "Janusia",
    "Juniper",
    "Mimosa",
    "Mulberry",
    "Natura",
    "Odora",
    "Pacifica",
    "Paloverde",
    "Park Greens",
    "Primrose",
    "Sanctuary",
    "Sycamore",
    "The Farmhouses",
    "Trixis",
    "Vardon",
    "Verona",
    "Victoria",
    "Violet",
    "Zinnia",
  ],
  "DAMAC Lagoons": [
    "Costa Brava",
    "Ibiza",
    "Malta",
    "Marbella",
    "Monte Carlo",
    "Morocco",
    "Mykonos",
    "Nice",
    "Portofino",
    "Santorini",
    "Venice",
  ],
  "Deira": [],
  "Discovery Gardens": [],
  "Downtown Dubai": ["Burj Khalifa District", "Old Town", "The Boulevard"],
  "Dubai Creek Harbour": [],
  "Dubai Hills Estate": [
    "Acacia",
    "Club Villas",
    "Collective",
    "Emerald Hills",
    "Executive Residences",
    "Fairway Vistas",
    "Golf Grove",
    "Golf Place",
    "Golf Suites",
    "Hills Park",
    "Hyde Residences",
    "Majestic Vistas",
    "Maple",
    "Mulberry",
    "Park Heights",
    "Parkway Vistas",
    "Sidra Villas",
  ],
  "Dubai Marina": [],
  "Dubai Silicon Oasis": ["Cedre Villas", "Semmer Villas"],
  "Dubai South": ["Expo City Dubai", "The Pulse"],
  "Dubai Sports City": [],
  "Dubai Studio City": [],
  "Emaar South": [
    "Expo Golf Villas",
    "Golf Links",
    "Greenview",
    "Parkside",
    "Saffron",
    "Urbana",
  ],
  "Emirates Hills": [],
  "Green Community (DIP)": [
    "Green Community East",
    "Green Community West",
    "The Market Apartments",
  ],
  "International City": [],
  "Jebel Ali Village": [],
  "Jumeirah": ["Jumeirah 1", "Jumeirah 2", "Jumeirah 3"],
  "Jumeirah Beach Residence (JBR)": [],
  "Jumeirah Golf Estates": [
    "Alandalus",
    "Earth",
    "Fire",
    "Flame Tree Ridge",
    "Orange Lake",
    "Redwood Avenue",
    "Redwood Park",
    "Sanctuary Falls",
    "Whispering Pines",
    "Wildflower",
  ],
  "Jumeirah Heights": [],
  "Jumeirah Islands": [],
  "Jumeirah Lake Towers (JLT)": [],
  "Jumeirah Park": [],
  "Jumeirah Village Circle (JVC)": [],
  "Jumeirah Village Triangle (JVT)": [],
  "Liwan": [],
  "Living Legends": [],
  "Majan": [],
  "Meydan / MBR City": [
    "District One",
    "Grand Views",
    "Meydan Gated Community",
    "Millennium Estates",
    "Sobha Hartland",
    "Sobha Hartland II",
  ],
  "Mira": [
    "Mira 1",
    "Mira 2",
    "Mira 3",
    "Mira 4",
    "Mira 5",
    "Mira Oasis 1",
    "Mira Oasis 2",
    "Mira Oasis 3",
  ],
  "Mirdif": ["Ghoroob", "Mirdif Hills", "Shorooq", "Uptown Mirdif"],
  "Motor City": ["Green Community Motor City", "Uptown Motor City"],
  "Mudon": [
    "Al Naseem",
    "Al Salam",
    "Arabella 1",
    "Arabella 2",
    "Arabella 3",
    "Mudon Al Ranim",
    "Mudon Views",
    "Rahat",
  ],
  "Mushrif": [],
  "Nad Al Sheba": [
    "Nad Al Sheba 1",
    "Nad Al Sheba 2",
    "Nad Al Sheba 3",
    "Nad Al Sheba 4",
    "Nad Al Sheba Gardens",
  ],
  "Palm Jumeirah": [
    "Garden Homes",
    "Golden Mile",
    "Marina Residences",
    "Shoreline Apartments",
    "Signature Villas",
  ],
  "Reem Community": [],
  "Remraam": ["Al Ramth", "Al Thamam"],
  "Rukan": [],
  "Serena": ["Bella Casa", "Casa Dora", "Casa Viva"],
  "The Lakes": ["Deema", "Forat", "Ghadeer", "Hattan", "Maeen", "Zulal"],
  "The Meadows": [
    "Meadows 1",
    "Meadows 2",
    "Meadows 3",
    "Meadows 4",
    "Meadows 5",
    "Meadows 6",
    "Meadows 7",
    "Meadows 8",
    "Meadows 9",
  ],
  "The Springs": [
    "Springs 1",
    "Springs 2",
    "Springs 3",
    "Springs 4",
    "Springs 5",
    "Springs 6",
    "Springs 7",
    "Springs 8",
    "Springs 9",
    "Springs 10",
    "Springs 11",
    "Springs 12",
    "Springs 14",
    "Springs 15",
  ],
  "The Sustainable City": [],
  "The Valley": [
    "Alana",
    "Avelia",
    "Avena",
    "Avena 2",
    "Eden",
    "Elea",
    "Elora",
    "Elva",
    "Farm Gardens",
    "Farm Gardens 2",
    "Farm Gardens 3",
    "Farm Grove",
    "Farm Grove 2",
    "Kaia",
    "Lilia",
    "Nara",
    "Nima",
    "Orania",
    "Ovelle",
    "Rivana",
    "Rivera",
    "Talia",
    "Velora",
    "Velora 2",
    "Venera",
    "Vindera",
  ],
  "Umm Suqeim": ["Umm Suqeim 1", "Umm Suqeim 2", "Umm Suqeim 3"],
  "Villanova": ["Amaranta", "La Quinta", "La Rosa", "La Tilia", "La Violeta"],
};

// Shown at the top of the area dropdown — where Carwaj actually operates.
export const PRIORITY_AREAS = [
  "Arabian Ranches 1",
  "Arabian Ranches 2",
  "Arabian Ranches 3",
  "Town Square",
  "Tilal Al Ghaf",
];

export const OTHER_AREAS = Object.keys(DUBAI_COMMUNITIES)
  .filter((a) => !PRIORITY_AREAS.includes(a))
  .sort((a, b) => a.localeCompare(b));

export const DUBAI_AREAS = [...PRIORITY_AREAS, ...OTHER_AREAS];

// An empty sub-community means the whole area is the community.
export function communityName(area: string, subCommunity: string) {
  return subCommunity || area;
}

// Fed straight into the Google Maps embed — specific enough to land on the
// right cluster rather than the middle of Dubai.
export function communityLocation(area: string, subCommunity: string) {
  return subCommunity
    ? `${subCommunity}, ${area}, Dubai, UAE`
    : `${area}, Dubai, UAE`;
}
